# Generated by Django 4.2.6 on 2023-10-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('router', 'Reititin'), ('switch', 'Kytkin'), ('nas', 'NAS')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
