# Generated by Django 4.2.6 on 2023-10-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_epdu_nas_networkmonitoringservice_proxmox_router_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('nas', 'NAS'), ('epdu', 'ePDU'), ('proxmox', 'Proxmox'), ('wlan', 'WLAN'), ('network_monitor', 'NetworkMonitoringService')], default='router', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('link', models.URLField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('ssid', models.CharField(blank=True, max_length=255, null=True, verbose_name='SSID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.URLField(blank=True, null=True, verbose_name='ePDU Domain')),
            ],
        ),
        migrations.DeleteModel(
            name='ePDU',
        ),
        migrations.DeleteModel(
            name='NAS',
        ),
        migrations.DeleteModel(
            name='NetworkMonitoringService',
        ),
        migrations.DeleteModel(
            name='Proxmox',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
        migrations.DeleteModel(
            name='WLAN',
        ),
    ]
