# Generated by Django 4.2.6 on 2023-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_delete_epdu_delete_nas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('router', 'router'), ('switch', 'switch'), ('nas', 'nas'), ('epdu', 'epdu'), ('proxmox', 'proxmox'), ('wlan', 'WLAN'), ('network_monitor', 'NetworkMonitoringService')], default='router', max_length=50),
        ),
    ]
