# Generated by Django 4.2.6 on 2023-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
